_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  RESIZER:
    WEIGHTS: "<path to resizer-R-18.pkl>"
    PARETO_SCALE_ST: 0
    PARETO_SCALE_END: 2
    ENCODER:
      NAME: "build_resnet_backbone"
      DEPTH: 18
      RES2_OUT_CHANNELS: 64
SOLVER:
  MAX_ITER:  180000
  BASE_LR_END: 5e-5
  WARMUP_ITERS: 1000
  LR_SCHEDULER_NAME: "WarmupConstCosineLR"
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  MAX_SIZE_TRAIN: 800
  MAX_SIZE_TEST: 800
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "../outputs/dyra/retinanet_r_101_2x"
