_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 18
  RESIZER:
    WEIGHTS: "<path to resizer-R-18.pkl>"
    PARETO_SCALE_ST: 0
    PARETO_SCALE_END: 5
    ENCODER:
      NAME: "build_resnet_backbone"
      DEPTH: 18
      RES2_OUT_CHANNELS: 64
SOLVER:
  MAX_ITER: 253536
  WARMUP_ITERS: 1000
  BASE_LR: 5e-3
  BASE_LR_END: 5e-5
  LR_SCHEDULER_NAME: "WarmupConstCosineLR"
  CHECKPOINT_PERIOD: 10564
  IMS_PER_BATCH: 1
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (1024,)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1024
TEST:
  EVAL_PERIOD: 10564
OUTPUT_DIR: "../outputs/dyra/dota/faster_rcnn_r_50_24ep"
